# Generated by Django 5.0.6 on 2024-07-01 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0002_alter_buses_placa'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='dni',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conductor',
            name='dni',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
    ]
