# Generated by Django 5.0.6 on 2024-07-01 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0003_cliente_dni_conductor_dni'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='clientes',
        ),
        migrations.RenameModel(
            old_name='Conductor',
            new_name='conductores',
        ),
        migrations.RenameModel(
            old_name='Entregable',
            new_name='entregables',
        ),
    ]
