# Generated by Django 5.0.6 on 2024-07-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0004_rename_cliente_clientes_rename_conductor_conductores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregables',
            name='dni',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
    ]
