# Generated by Django 5.0.6 on 2024-07-03 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0006_entregables_apellido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entregables',
            old_name='fechaEntrega',
            new_name='fecha',
        ),
    ]
