# Generated by Django 5.0.6 on 2024-07-03 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0007_rename_fechaentrega_entregables_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entregables',
            old_name='fecha',
            new_name='fechaEntrega',
        ),
    ]
