# Generated by Django 5.0.6 on 2024-07-04 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0008_rename_fecha_entregables_fechaentrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregables',
            name='desde',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entregables',
            name='lugar',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
