# Generated by Django 5.0.6 on 2024-07-18 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0011_entrada_delete_nombre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entrada',
        ),
    ]
