# Generated by Django 5.0.6 on 2024-07-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0013_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtenderClinetes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=60)),
                ('desde', models.CharField(max_length=80)),
                ('lugar', models.CharField(max_length=80)),
                ('nAsiento', models.CharField(max_length=80)),
                ('costo', models.CharField(max_length=7)),
                ('fechaEntrega', models.DateField()),
            ],
        ),
    ]
