# Generated by Django 5.0.6 on 2024-07-26 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0015_rename_lugar_atenderclinetes_llegada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atenderclinetes',
            name='fechaEntrega',
        ),
    ]
